---
# VPC default variables
vpc_state: present

vpc_name: ansible
vpc_cidr_block: 172.16.0.0/16
vpc_resource_tags: {
  "Name":"{{ vpc_name }}"
  }

database_subnets: []
web_cidr_block: 172.16.20.0/24

# EC2 default variables
env: ansible
instance_count: 1
instance_type: t2.micro

# RDS default variables
db_instance_class: db.t2.micro

# Cloudfront default_caller
cdn_caller_reference: 20190215120000